# Generated by Django 6.0.1 on 2026-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znuny_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='pt', max_length=10)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('symptom', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'title'],
            },
        ),
    ]
