# Generated by Django 6.0.1 on 2026-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='f_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
