# Generated by Django 6.0.1 on 2026-01-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('nv', 'Novo'), ('ex', 'EM_EXECUCAO'), ('cn', 'CONCLUIDO')], default='nv', max_length=2)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('target_audience', models.CharField(choices=[('ges', 'Gestores'), ('tec', 'Tecnicos'), ('out', 'Outros')], default='out', max_length=3)),
                ('kpis_displayed', models.CharField(blank=True, max_length=255, null=True)),
                ('analytical_or_macro', models.CharField(choices=[('an', 'Analitico'), ('ma', 'Macro')], default='ma', max_length=2)),
                ('data_source', models.CharField(max_length=111)),
                ('panel_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('color_preference', models.CharField(blank=True, max_length=60, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json', models.FileField(blank=True, null=True, upload_to='dashboards/json/%Y/%m/')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.categoria')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cliente')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='dashboards/images/%Y/%m/')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.dashboard')),
            ],
        ),
    ]
