# Generated by Django 6.0 on 2026-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('silver', 'Silver'), ('gold', 'Gold')], default='standard', max_length=10),
        ),
    ]
