# Generated by Django 6.0 on 2026-04-17 16:25

from django.db import migrations, models


def migrate_dashboard_categories_and_tiers(apps, schema_editor):
    Dashboard = apps.get_model('dashboard', 'Dashboard')
    Cliente = apps.get_model('dashboard', 'Cliente')

    # Preserve the existing single category relation into the new M2M field.
    for dashboard in Dashboard.objects.exclude(category__isnull=True):
        dashboard.categories.add(dashboard.category_id)

    # Existing "standard" clients are migrated to "silver".
    Cliente.objects.filter(tier='standard').update(tier='silver')


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboard_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dashboards', to='dashboard.categoria'),
        ),
        migrations.RunPython(migrate_dashboard_categories_and_tiers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dashboard',
            name='category',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tier',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=10),
        ),
    ]
