# Generated by Django 6.0.1 on 2026-01-31 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_categoria_owner_dashboard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardimage',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_images', to='dashboard.dashboard'),
        ),
    ]
