# Generated by Django 6.0 on 2026-04-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_dashboard_category_dashboard_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='analytical_or_macro',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='color_preference',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='kpis_displayed',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='panel_preference',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='target_audience',
        ),
    ]
