# Generated by Django 6.0 on 2026-04-20 23:08

from django.db import migrations


def migrate_roles(apps, schema_editor):
    OrganizationMember = apps.get_model('dashboard', 'OrganizationMember')
    # Update admin -> administrador
    OrganizationMember.objects.filter(role='admin').update(role='administrador')
    # Update member -> membro
    OrganizationMember.objects.filter(role='member').update(role='membro')
    # Update viewer -> membro (binary model)
    OrganizationMember.objects.filter(role='viewer').update(role='membro')

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_organization_code_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_roles),
    ]
