# Generated by Django 6.0.1 on 2026-04-21 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_migrate_roles_to_new_strings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_dashboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
