# Generated by Django 6.0.1 on 2026-04-21 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_dashboard_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
