# Generated by Django 6.0.1 on 2026-04-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_cliente_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cliente'),
        ),
    ]
