# Generated by Django 6.0.1 on 2026-04-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_dashboard_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
