# Generated by Django 6.0.1 on 2026-05-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_comment_to_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='comment',
        ),
    ]
