# Generated by Django 6.0.1 on 2026-05-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_dashboard_comment'),
        ('faq', '0002_faq_f_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='faq',
            field=models.ForeignKey(default=446, on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='faq.faq'),
            preserve_default=False,
        ),
    ]
