# Generated by Django 6.0.1 on 2026-06-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0014_dashboard_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('html_graphics', 'HTML Graphics JSON'), ('html_text', 'HTML / Text Panel'), ('business_text', 'Business Text'), ('dashboard_json', 'Dashboard JSON'), ('sql', 'SQL Query'), ('javascript', 'JavaScript'), ('css', 'CSS'), ('svg', 'SVG')], max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Ativo')], default='draft', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='forge/thumbnails/%Y/%m/')),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('copy_count', models.PositiveIntegerField(default=0)),
                ('export_count', models.PositiveIntegerField(default=0)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forge_codes_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forge_codes', to='dashboard.organization')),
            ],
            options={
                'verbose_name': 'Código',
                'verbose_name_plural': 'Códigos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('content', models.JSONField()),
                ('changelog', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forge.codeentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
                'ordering': ['-created_at'],
            },
        ),
    ]
