# Generated by Django 6.0.1 on 2026-06-26 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeentry',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_forge_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
