# Generated by Django 6.0.1 on 2026-06-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0002_add_favorited_by_to_codeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeentry',
            name='tags',
        ),
    ]
