# Generated by Django 6.0.1 on 2026-07-08 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_dashboard_faq'),
        ('forge', '0005_add_business_charts_canvas_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='dashboard.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Agente',
                'verbose_name_plural': 'Logs do Agente',
                'ordering': ['-created_at'],
            },
        ),
    ]
